### ISSUE TITLE
Can there be an executable that takes input files?

### ISSUE THREAD

**Issue by johanneskiesel** [hwanheelee1993/KPQA#1]
Hi,

We are organizing a shared task on question answering (https://scai.info/scai-qrecc/) and are looking for evaluation metrics. We would also be interested in this one, but it seems rather complex to integrate this into our evaluation pipeline.

Can you provide an executable that just takes input files? The format is not so important for us, I think we can adapt here. But for illustration, it could be a JSON file with objects like this:
```
{
  "reference-answer": "<text>",
  "question": "<text>",
  "generated-answer": "<text>"
}
```

And the output would be just the list of KPQA values.

That would be very helpful!

**Comment by hwanheelee1993** [comment]
I'm really sorry for the too late reply. I missed the comment.

Thank you so much for the interest and it would be really helpful.

I'll make it by tomorrow and share in this repo. (If it's not too late..., anyway I'll share it for the easy usage)

Thanks

Hwanhee Lee

**Comment by johanneskiesel** [comment]
Thank you! We still have some time left to experiment with metrices ;)

**Comment by hwanheelee1993** [comment]
I update the code for easy usage and provide the sample input file (.csv format). Feel free to ask any questions!

**Comment by johanneskiesel** [comment]
I needed to do a few straightforward modifications to get it to run with the CPU, but I was now able to run `compute_KPQA.py`.

Thanks again!
